services:
  database:
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql
      - ./init_db.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_PASSWORD=db_password
      - POSTGRES_USER=mynd
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    command:
      - start-dev
    depends_on:
      - database
    ports:
      - "8081:8080"
    environment:
      - KC_DB=postgres
      - KC_DB_URL_HOST=database
      - KC_DB_USERNAME=mynd
      - KC_DB_PASSWORD=db_password
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=admin
  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9999:9000"
      - "9001:9001"
    environment:
      MINIO_ACCESS_KEY: "minioadmin"
      MINIO_SECRET_KEY: "minioadmin"
      MINIO_ROOT_USER: "admin"
      MINIO_ROOT_PASSWORD: "admin1234567"
    volumes:
      - ./data:/data
    command: server /data --address "0.0.0.0:9000" --console-address "0.0.0.0:9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 5s
      timeout: 5s
      retries: 5
  # Mail rcv simulator
  maildev:
    image: maildev/maildev
    ports:
      - "1080:1080"
      - "1025:1025"

volumes:
  db_data:
