import {
  IconBook,
  IconBook2,
  IconBookmark,
  IconBrain,
  IconBrandSpotify,
  IconBrandYoutube,
  IconBulb,
  IconClipboard,
  IconCode,
  IconFileDescription,
  IconFileTypePdf,
  IconHeadphones,
  IconLink,
  IconMath,
  IconMusic,
  IconNote,
  IconNotebook,
  IconPalette,
  IconPhoto,
  IconStar,
  IconTarget,
  IconTrophy,
  IconVideo,
  IconWorld,
  type Icon,
} from '@tabler/icons-react';
import type { ContentElementType } from '../../schemas/content-element.ts';

export const CONTENT_ICONS: Record<string, Icon> = {
  IconFileTypePdf,
  IconFileDescription,
  IconVideo,
  IconBrandYoutube,
  IconHeadphones,
  IconBrandSpotify,
  IconPhoto,
  IconLink,
  IconBook,
  IconBook2,
  IconNotebook,
  IconNote,
  IconBookmark,
  IconBulb,
  IconBrain,
  IconCode,
  IconMath,
  IconPalette,
  IconMusic,
  IconStar,
  IconTarget,
  IconTrophy,
  IconWorld,
  IconClipboard,
};

export const DEFAULT_ICON_BY_TYPE: Record<ContentElementType, string> = {
  PDF: 'IconFileTypePdf',
  VIDEO_FILE: 'IconVideo',
  YOUTUBE_LINK: 'IconBrandYoutube',
  AUDIO_FILE: 'IconHeadphones',
  SPOTIFY_LINK: 'IconBrandSpotify',
  IMAGE: 'IconPhoto',
  RTF: 'IconFileDescription',
  URI: 'IconLink',
};

export const resolveIcon = (name: string | undefined | null): Icon | null =>
  (name && CONTENT_ICONS[name]) || null;
