name: Build
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - dev

permissions:
  contents: read
  packages: write

jobs:
  build-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        name: Checkout
      - name: Setup GraalVM
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: 21
          distribution: 'graalvm-community'
          cache: maven

      - name: Verify backend
        working-directory: mynd-backend
        run: |
          chmod +x mvnw
          ./mvnw verify -B

      - name: Build backend
        working-directory: mynd-backend
        run: |
          chmod +x mvnw
          ./mvnw package -Dnative -DskipTests

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./mynd-backend
          file: mynd-backend/src/main/docker/Dockerfile
          push: false
          load: true
          tags: local-test-image:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          push: false
          load: true
          tags: local-test-image:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            VITE_KEYCLOAK_URL=http://127.0.0.1:8081/
            VITE_KEYCLOAK_REALM=mynd-realm
            VITE_KEYCLOAK_CLIENT_ID=mynd
            VITE_MYND_BACKEND_URI=http://127.0.0.1:8080
      - name: Verify Image
        run: docker images local-test-image:latest

  build-keycloak:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: false
          load: true
          tags: local-test-image:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
          file: ./keycloak/Dockerfile
      - name: Verify Image
        run: docker images local-test-image:latest
